name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_ALIYUN_USERNAME }}
          password: ${{ secrets.DOCKER_ALIYUN_PASSWD }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          export DOCKER_HOST=tcp://localhost:2376
          export DOCKER_TLS_CERTDIR="/certs"
          export DOCKER_TLS_VERIFY=1
          export DOCKER_CERT_PATH="/certs/client"
          docker context create builders
      # https://github.com/docker/setup-buildx-action
      # https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          # buildkitd-flags: --debug
          endpoint: builders
        env:
          DOCKER_HOST: "tcp://localhost:2376"
          DOCKER_TLS_CERTDIR: "/certs"
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: "/certs/client"
      #
      # Debug
      #
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/sh-lijian/note-mate-wx-connector:latest